<?php
// admin/sms_settings.php — Simplified SMS/OTP Configuration
require_once '../includes/layout.php';
require_once '../includes/sms_config.php';
checkRole('admin');

$msg = '';
$msgType = 'success';
$configFile = __DIR__ . '/../includes/sms_config.php';

// ── Handle Save ───────────────────────────────────────────────
if (isset($_POST['save_sms'])) {
    $provider    = $_POST['provider'] === 'msg91' ? 'msg91' : ($_POST['provider'] === 'mock' ? 'mock' : 'fast2sms');
    $fast2smsKey = trim($_POST['fast2sms_api_key'] ?? '');
    $msg91Key    = trim($_POST['msg91_auth_key'] ?? '');
    $msg91Tmpl   = trim($_POST['msg91_template_id'] ?? '');
    $msg91Sender = trim($_POST['msg91_sender_id'] ?? 'OTRSYS');
    $expiry      = max(1, min(60, (int)($_POST['otp_expiry'] ?? 10)));
    $digits      = in_array((int)$_POST['otp_digits'], [4,6]) ? (int)$_POST['otp_digits'] : 6;
    $devMode     = isset($_POST['dev_mode']) ? 'true' : 'false';

    $content = "<?php\n";
    $content .= "// includes/sms_config.php — Auto-generated by admin panel\n";
    $content .= "define('SMS_PROVIDER', '{$provider}');\n\n";
    $content .= "// Fast2SMS\n";
    $content .= "define('FAST2SMS_API_KEY', '" . addslashes($fast2smsKey) . "');\n\n";
    $content .= "// MSG91\n";
    $content .= "define('MSG91_AUTH_KEY',    '" . addslashes($msg91Key) . "');\n";
    $content .= "define('MSG91_TEMPLATE_ID', '" . addslashes($msg91Tmpl) . "');\n";
    $content .= "define('MSG91_SENDER_ID',   '" . addslashes($msg91Sender) . "');\n\n";
    $content .= "// OTP\n";
    $content .= "define('OTP_EXPIRY_MINUTES', {$expiry});\n";
    $content .= "define('OTP_DIGITS', {$digits});\n\n";
    $content .= "// Dev Mode\n";
    $content .= "define('SMS_DEV_MODE', {$devMode});\n";
    $content .= "?>\n";

    if (file_put_contents($configFile, $content) !== false) {
        $msg = '✅ SMS settings saved successfully!';
        // Force reload constants for current execution
        header("Location: sms_settings.php?success=1");
        exit();
    }
}

if (isset($_GET['success'])) $msg = '✅ SMS settings saved successfully!';

// ── Handle Test ───────────────────────────────────────────────
$testResult = null;
if (isset($_POST['test_sms'])) {
    require_once '../includes/sms_helper.php';
    $testMobile = preg_replace('/[^0-9]/', '', trim($_POST['test_mobile'] ?? ''));
    if (strlen($testMobile) !== 10) {
        $testResult = ['success' => false, 'message' => 'Invalid mobile number. Please enter exactly 10 digits.'];
    } else {
        $testResult = sendOtpSMS($testMobile, '123456');
        if (!empty($testResult['dev_otp'])) {
            $testResult['message'] = "Test OTP is: " . $testResult['dev_otp'] . " (Sent in Mock Mode).";
        }
    }
}

renderHeader('SMS Settings');
renderSidebar('admin');
?>

<div class="card" style="padding: 30px;">
    <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom: 25px; border-bottom: 2px solid #f1f5f9; padding-bottom: 15px;">
        <div>
            <h2 style="margin:0;"><i class="fas fa-sms" style="color:var(--primary); margin-right:10px;"></i> SMS Configuration</h2>
            <p style="color:#64748b; margin:5px 0 0;">Link your portal to Fast2SMS for real-world OTP logins</p>
        </div>
        <div style="display:flex; gap:10px;">
            <a href="https://www.fast2sms.com" target="_blank" class="btn" style="background:#0369a1; color:#fff; border:none; padding:8px 15px; font-size:0.85rem;">
                <i class="fas fa-external-link-alt"></i> Fast2SMS.com
            </a>
        </div>
    </div>

    <?php if ($msg): ?>
    <div style="background:#f0fdf4; color:#16a34a; border:1px solid #bbf7d0; padding:15px; border-radius:12px; margin-bottom:25px; font-weight:700;">
        <i class="fas fa-check-circle"></i> <?php echo $msg; ?>
    </div>
    <?php endif; ?>

    <form method="POST">
        <div style="display:grid; grid-template-columns: 1.5fr 1fr; gap: 35px;">
            
            <!-- Left Side: Key Inputs -->
            <div>
                <div style="background:#f8fafc; border:1.5px solid #e2e8f0; border-radius:16px; padding:25px; box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1);">
                    <div style="font-weight:900; font-size:0.8rem; text-transform:uppercase; letter-spacing:1px; color:#6366f1; margin-bottom:20px;">
                        <i class="fas fa-satellite-dish"></i> API Key Setup
                    </div>

                    <div class="form-group">
                        <label class="form-label" style="font-weight:700; color:#1e293b;">Select SMS Provider</label>
                        <select name="provider" class="form-control" id="providerSelect" style="height:50px; font-weight:600;" onchange="toggleFields()">
                            <option value="fast2sms" <?php echo SMS_PROVIDER==='fast2sms'?'selected':''; ?>>⚡ Fast2SMS (Recommended)</option>
                            <option value="msg91" <?php echo SMS_PROVIDER==='msg91'?'selected':''; ?>>📨 MSG91</option>
                            <option value="mock" <?php echo SMS_PROVIDER==='mock'?'selected':''; ?>>🧪 Mock Mode (Test only)</option>
                        </select>
                    </div>

                    <!-- Fast2SMS Box -->
                    <div id="fast2smsBox" style="margin-top:20px; <?php echo SMS_PROVIDER!=='fast2sms'?'display:none;':''; ?>">
                        <div class="form-group">
                            <label class="form-label" style="font-weight:700; color:#1e293b; display:flex; align-items:center; gap:8px;">
                                <i class="fas fa-key" style="color:#f59e0b;"></i> Fast2SMS API Key
                            </label>
                            <input type="text" name="fast2sms_api_key" class="form-control" 
                                   value="<?php echo htmlspecialchars(FAST2SMS_API_KEY === ',' ? '' : FAST2SMS_API_KEY); ?>" 
                                   placeholder="Click 'Dev API' on Fast2SMS dashboard to get your key"
                                   style="height:50px; border:2px solid #cbd5e1; font-family:'Courier New',monospace; font-weight:700;">
                            <small style="color:#64748b; margin-top:8px; display:block;">
                                <i class="fas fa-info-circle"></i> Recharge your Fast2SMS wallet to activate this key.
                            </small>
                        </div>
                    </div>

                    <!-- MSG91 Box -->
                    <div id="msg91Box" style="margin-top:20px; <?php echo SMS_PROVIDER!=='msg91'?'display:none;':''; ?>">
                        <div class="form-group">
                            <label class="form-label">Auth Key</label>
                            <input type="text" name="msg91_auth_key" class="form-control" value="<?php echo htmlspecialchars(MSG91_AUTH_KEY === ',' ? '' : MSG91_AUTH_KEY); ?>">
                        </div>
                        <div class="form-group">
                            <label class="form-label">Template ID</label>
                            <input type="text" name="msg91_template_id" class="form-control" value="<?php echo htmlspecialchars(MSG91_TEMPLATE_ID === ',' ? '' : MSG91_TEMPLATE_ID); ?>">
                        </div>
                    </div>

                    <button type="submit" name="save_sms" class="btn btn-primary" style="width:100%; height:55px; font-weight:800; font-size:1.1rem; margin-top:15px; background:linear-gradient(135deg,#0369a1,#0b70b7);">
                        <i class="fas fa-save"></i> Save Settings
                    </button>
                </div>
            </div>

            <!-- Right Side: Config & Stats -->
            <div>
                <div style="background:#fff; border:1.5px solid #e2e8f0; border-radius:16px; padding:20px;">
                    <div style="font-weight:900; font-size:0.8rem; text-transform:uppercase; letter-spacing:1px; color:#475569; margin-bottom:15px;">
                        <i class="fas fa-tools"></i> OTP Policy
                    </div>
                    
                    <div class="form-group">
                        <label class="form-label">OTP Digits</label>
                        <select name="otp_digits" class="form-control">
                            <option value="4" <?php echo OTP_DIGITS==4?'selected':''; ?>>4 Digits</option>
                            <option value="6" <?php echo OTP_DIGITS==6?'selected':''; ?>>6 Digits (Stronger)</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label class="form-label">Valid for (Minutes)</label>
                        <input type="number" name="otp_expiry" class="form-control" value="<?php echo OTP_EXPIRY_MINUTES; ?>" min="1" max="60">
                    </div>

                    <label style="display:flex; align-items:center; gap:10px; cursor:pointer; background:#fff7ed; padding:12px; border-radius:10px; border:1px solid #ffedd5;">
                        <input type="checkbox" name="dev_mode" <?php echo SMS_DEV_MODE?'checked':''; ?> style="width:20px; height:20px;">
                        <div>
                            <span style="font-weight:800; color:#9a3412;">Developer / Test Mode</span>
                            <small style="display:block; color:#c2410c;">OTP shows on screen, no real SMS cost.</small>
                        </div>
                    </label>
                </div>

                <!-- Live Status -->
                <div style="margin-top:20px; background:#eff6ff; border:1.5px solid #bfdbfe; border-radius:16px; padding:20px;">
                    <div style="font-weight:800; color:#1d4ed8; margin-bottom:10px;">System Status</div>
                    <div style="font-size:0.9rem; color:#1e40af; line-height:1.8;">
                        <div><i class="fas fa-check-circle" style="width:20px;"></i> Active Provider: <strong><?php echo strtoupper(SMS_PROVIDER); ?></strong></div>
                        <div><i class="fas fa-shield-alt" style="width:20px;"></i> Key Status: <strong><?php echo (FAST2SMS_API_KEY && FAST2SMS_API_KEY !== ',') ? '✅ Configured' : '❌ NOT SET'; ?></strong></div>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <!-- Test Tool -->
    <div style="margin-top:40px; padding-top:30px; border-top:2px solid #f1f5f9;">
        <h3 style="margin:0 0 20px 0;"><i class="fas fa-vial" style="color:#10b981;"></i> Test SMS Sending</h3>
        <form method="POST" style="display:flex; gap:15px; align-items:flex-end;">
            <div style="flex:1;">
                <label class="form-label">Mobile Number</label>
                <input type="text" name="test_mobile" class="form-control" placeholder="10 digit mobile">
            </div>
            <button type="submit" name="test_sms" class="btn" style="background:#10b981; color:#fff; height:50px; font-weight:800; padding:0 30px;">
                Send Test OTP
            </button>
        </form>
        
        <?php if ($testResult): ?>
        <div style="margin-top:15px; padding:15px; border-radius:10px; <?php echo $testResult['success']?'background:#f0fdf4; color:#16a34a; border:1px solid #bbf7d0;':'background:#fef2f2; color:#dc2626; border:1px solid #fecaca;'; ?>">
             <i class="fas <?php echo $testResult['success']?'fa-check-circle':'fa-times-circle'; ?>"></i> <?php echo $testResult['message']; ?>
        </div>
        <?php endif; ?>
    </div>
</div>

<script>
function toggleFields() {
    const provider = document.getElementById('providerSelect').value;
    document.getElementById('fast2smsBox').style.display = (provider === 'fast2sms') ? 'block' : 'none';
    document.getElementById('msg91Box').style.display = (provider === 'msg91') ? 'block' : 'none';
}
// Initial check
document.addEventListener('DOMContentLoaded', toggleFields);
</script>

<?php renderFooter(); ?>
