<?php
// includes/sms_config.php — Auto-generated by admin panel
define('SMS_PROVIDER', 'fast2sms');

// Fast2SMS
define('FAST2SMS_API_KEY', 'r9nTkelScG7aP7bia9BJksKY6xQqv8HyQxn4ENAisWDCTkJZdjRvinaCKSvN');

// MSG91
define('MSG91_AUTH_KEY',    '');
define('MSG91_TEMPLATE_ID', '');
define('MSG91_SENDER_ID',   'OTRSYS');

// OTP
define('OTP_EXPIRY_MINUTES', 10);
define('OTP_DIGITS', 6);

// Dev Mode
define('SMS_DEV_MODE', false);
?>
