<?php
// includes/sms_config.php — Auto-generated by admin panel
define('SMS_PROVIDER', 'authkey');

// Fast2SMS
define('FAST2SMS_API_KEY', 'r9nTkelScG7aP7bia9BJksKY6xQqv8HyQxn4ENAisWDCTkJZdjRvinaCKSvN');

// MSG91
define('MSG91_AUTH_KEY',    '');
define('MSG91_TEMPLATE_ID', '');
define('MSG91_SENDER_ID',   'OTRSYS');

// AuthKey.io
define('AUTHKEY_API_KEY', 'fa9e3ecc0750f0ac');
define('AUTHKEY_SID',     '38845');

// OTP
define('OTP_EXPIRY_MINUTES', 5);
define('OTP_DIGITS', 4); // User's rand(1000, 9999) implies 4 digits

// Dev Mode
define('SMS_DEV_MODE', false);
?>
